version: '3.8'
services:
  nodejs-app:
    build: ./ 
    ports:
      - "5000:5001"

  loki:
    build:
      context: ./
      dockerfile: Dockerfile-loki
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config/local-config.yaml:/etc/loki/local-config.yaml
    ports:
      - "3100:3100"

  promtail:
    image: grafana/promtail:latest
    command: -config.file=/etc/promtail/local-config.yaml
    volumes:
      - ./promtail-config/local-config.yaml:/etc/promtail/local-config.yaml
      - /var/log:/var/log
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    depends_on:
      - loki
